"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Map as MapLibreMap, Marker } from "maplibre-gl";
import { AlertTriangle, BarChart3, Bell, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Contrast, Database, Layers3, MapPin, Menu, MoreHorizontal, Navigation, Plus, Route, Search, Sparkles, SunMoon, UsersRound, Wrench, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { BackendGeocodingProvider, BackendRoutingProvider, type Coordinate } from "@/lib/map-providers";
import { csvEngineers, csvJobs, csvMeta } from "@/lib/csv-data.generated";
import { minutesLabel, optimizeVrptw, type Engineer, type Job, type OptimizationResult, type Region } from "@/lib/vrptw";

type ThemeId = "light" | "dark" | "beeline" | "ocean" | "graphite" | "contrast";
type ViewId = "plan" | "requests" | "team" | "analytics";
type RoutingState = "loading" | "ready" | "fallback";
const sourceJobs = csvJobs as Job[]; const sourceEngineers = csvEngineers as Engineer[];
const regionCenters: Record<Region, Coordinate> = { "Восток": [37.73, 55.73], "Юго-восток": [37.72, 55.57], "Югоцентр": [37.61, 55.67] };
const themes: Array<{ id: ThemeId; name: string; colors: string[] }> = [
  { id: "light", name: "Светлая", colors: ["#fff", "#6547e7"] }, { id: "dark", name: "Тёмная", colors: ["#111522", "#8e7cff"] }, { id: "beeline", name: "Билайн", colors: ["#ffd400", "#151515"] }, { id: "ocean", name: "Океан", colors: ["#e9fbff", "#007f8b"] }, { id: "graphite", name: "Графит", colors: ["#dfe3e8", "#38414d"] }, { id: "contrast", name: "Высокий контраст", colors: ["#fff", "#0047ff"] },
];
function Logo() { return <div className="brand"><span className="brand-mark"><Route size={18} /></span><span>FieldFlow</span></div>; }
function formatDistance(value: number) { return `${value.toFixed(1).replace(".", ",")} км`; }
function routeCoordinates(engineer: Engineer, list: Job[], baseline = false) { return [engineer.start, ...list.filter(job => (baseline ? job.baselineEngineerId : job.engineerId) === engineer.id).sort((a, b) => a.windowStart - b.windowStart).map(job => job.coordinates)]; }

function MapCanvas({ visibleJobs, baselineJobs, engineers, selectedEngineerId, selectedJobId, compare, onSelectEngineer, onSelectJob, onRoutingState }: { visibleJobs: Job[]; baselineJobs: Job[]; engineers: Engineer[]; selectedEngineerId: string | null; selectedJobId: string | null; compare: boolean; onSelectEngineer: (id: string) => void; onSelectJob: (id: string) => void; onRoutingState: (state: RoutingState) => void }) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const markersRef = useRef<Marker[]>([]); const loadedRef = useRef(false); const [mapReady, setMapReady] = useState(false); const [roadRoutes, setRoadRoutes] = useState<Record<string, Coordinate[]>>({}); const [routeStatus, setRouteStatus] = useState<RoutingState>("loading");
  const visibleEngineerIds = useMemo(() => new Set(visibleJobs.map(job => job.engineerId).filter(Boolean)), [visibleJobs]); const visibleEngineers = useMemo(() => engineers.filter(engineer => visibleEngineerIds.has(engineer.id)), [engineers, visibleEngineerIds]);
  const latestRef = useRef({ visibleJobs, visibleEngineers, compare }); useEffect(() => { latestRef.current = { visibleJobs, visibleEngineers, compare }; }, [visibleJobs, visibleEngineers, compare]);
  useEffect(() => { let cancelled = false; const provider = new BackendRoutingProvider("osrm"); void (async () => { const results: Array<readonly [string, Coordinate[], boolean]> = []; for (let offset = 0; offset < visibleEngineers.length; offset += 5) { const batch = await Promise.all(visibleEngineers.slice(offset, offset + 5).map(async engineer => { const fallback = routeCoordinates(engineer, visibleJobs); if (fallback.length < 2) return [engineer.id, fallback, false] as const; try { const result = await provider.buildRoute({ points: fallback.slice(0, 25), mode: "driving" }); return [engineer.id, result.geometry.coordinates as Coordinate[], result.provider !== "osrm"] as const; } catch { return [engineer.id, fallback, true] as const; } })); results.push(...batch); if (cancelled) return; } if (cancelled) return; const state: RoutingState = results.some(item => item[2]) ? "fallback" : "ready"; setRoadRoutes(Object.fromEntries(results.map(([id, coords]) => [id, coords]))); setRouteStatus(state); onRoutingState(state); })(); return () => { cancelled = true; }; }, [visibleEngineers, visibleJobs, onRoutingState]);
  const routeData = useMemo<GeoJSON.FeatureCollection<GeoJSON.LineString>>(() => ({ type: "FeatureCollection", features: visibleEngineers.map(engineer => ({ type: "Feature", properties: { id: engineer.id, color: engineer.color, selected: selectedEngineerId === engineer.id ? 1 : 0 }, geometry: { type: "LineString", coordinates: roadRoutes[engineer.id] ?? routeCoordinates(engineer, visibleJobs) } })) }), [visibleEngineers, visibleJobs, selectedEngineerId, roadRoutes]);
  const baselineData = useMemo<GeoJSON.FeatureCollection<GeoJSON.LineString>>(() => ({ type: "FeatureCollection", features: visibleEngineers.map(engineer => ({ type: "Feature", properties: { id: engineer.id, color: engineer.color }, geometry: { type: "LineString", coordinates: routeCoordinates(engineer, baselineJobs, true) } })) }), [visibleEngineers, baselineJobs]);
  const fitVisible = useCallback(async () => { const map = mapRef.current; if (!map || !loadedRef.current) return; const all = [...visibleJobs.map(job => job.coordinates), ...visibleEngineers.map(engineer => engineer.start)]; if (!all.length) return; const { LngLatBounds } = await import("maplibre-gl"); const bounds = new LngLatBounds(all[0], all[0]); all.slice(1).forEach(point => bounds.extend(point)); map.fitBounds(bounds, { padding: 48, maxZoom: 12.5, duration: 500 }); }, [visibleJobs, visibleEngineers]);
  useEffect(() => { let cancelled = false; void import("maplibre-gl").then(maplibre => { if (cancelled || !containerRef.current || mapRef.current) return; maplibre.setWorkerUrl("/maplibre/maplibre-gl-worker.mjs"); const map = new maplibre.Map({ container: containerRef.current, center: [37.67, 55.67], zoom: 9.6, attributionControl: false, style: { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors" } }, layers: [{ id: "osm", type: "raster", source: "osm" }] } }); map.addControl(new maplibre.AttributionControl({ compact: true }), "bottom-right"); map.on("style.load", () => { loadedRef.current = true; const current = latestRef.current; const initial: GeoJSON.FeatureCollection<GeoJSON.LineString> = { type: "FeatureCollection", features: current.visibleEngineers.map(engineer => ({ type: "Feature", properties: { id: engineer.id, color: engineer.color, selected: 0 }, geometry: { type: "LineString", coordinates: routeCoordinates(engineer, current.visibleJobs) } })) }; map.addSource("baseline-routes", { type: "geojson", data: initial }); map.addLayer({ id: "baseline-routes", type: "line", source: "baseline-routes", layout: { visibility: current.compare ? "visible" : "none" }, paint: { "line-color": ["get", "color"], "line-width": 4, "line-opacity": .38, "line-dasharray": [1, 1.5] } }); map.addSource("routes", { type: "geojson", data: initial }); map.addLayer({ id: "route-shadow", type: "line", source: "routes", paint: { "line-color": "#fff", "line-width": ["case", ["==", ["get", "selected"], 1], 10, 7], "line-opacity": .8 } }); map.addLayer({ id: "routes", type: "line", source: "routes", paint: { "line-color": ["get", "color"], "line-width": ["case", ["==", ["get", "selected"], 1], 6, 3.5], "line-opacity": ["case", ["==", ["get", "selected"], 1], 1, .72] } }); setMapReady(true); }); mapRef.current = map; }); return () => { cancelled = true; markersRef.current.forEach(marker => marker.remove()); mapRef.current?.remove(); mapRef.current = null; loadedRef.current = false; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map || !loadedRef.current) return; (map.getSource("routes") as { setData: (data: GeoJSON.FeatureCollection) => void } | undefined)?.setData(routeData); (map.getSource("baseline-routes") as { setData: (data: GeoJSON.FeatureCollection) => void } | undefined)?.setData(baselineData); if (map.getLayer("baseline-routes")) map.setLayoutProperty("baseline-routes", "visibility", compare ? "visible" : "none"); markersRef.current.forEach(marker => marker.remove()); markersRef.current = []; void import("maplibre-gl").then(({ Marker }) => { if (!mapRef.current) return; visibleEngineers.forEach(engineer => { const el = document.createElement("button"); el.className = `engineer-map-marker${selectedEngineerId === engineer.id ? " selected" : ""}`; el.textContent = engineer.initials; el.style.setProperty("--marker", engineer.color); el.title = engineer.name; el.onclick = () => onSelectEngineer(engineer.id); markersRef.current.push(new Marker({ element: el }).setLngLat(engineer.start).addTo(mapRef.current!)); }); visibleJobs.forEach((job, index) => { if (!job.engineerId) return; const engineer = engineers.find(item => item.id === job.engineerId); if (!engineer) return; const el = document.createElement("button"); el.className = `job-map-marker${selectedJobId === job.id ? " selected" : ""}`; el.textContent = String(index + 1); el.style.setProperty("--marker", engineer.color); el.title = `№ ${job.id} · ${job.address}`; el.onclick = () => onSelectJob(job.id); markersRef.current.push(new Marker({ element: el }).setLngLat(job.coordinates).addTo(mapRef.current!)); }); }); }, [routeData, baselineData, compare, selectedEngineerId, selectedJobId, visibleEngineers, visibleJobs, engineers, onSelectEngineer, onSelectJob, mapReady]);
  useEffect(() => { const map = mapRef.current; if (!map || !loadedRef.current) return; const job = visibleJobs.find(item => item.id === selectedJobId); if (job) map.flyTo({ center: job.coordinates, zoom: 13.3, duration: 500 }); else void fitVisible(); }, [selectedJobId, selectedEngineerId, visibleJobs, fitVisible]);
  return <div className="map-canvas real-map" aria-label="Интерактивная карта маршрутов инженеров"><div ref={containerRef} className="maplibre-host" /><div className="map-tools"><button aria-label="Показать все маршруты" onClick={() => void fitVisible()}><Layers3 size={17} /></button><span /><button aria-label="Увеличить карту" onClick={() => mapRef.current?.zoomIn()}>+</button><button aria-label="Уменьшить карту" onClick={() => mapRef.current?.zoomOut()}>−</button></div><div className={`map-caption ${routeStatus}`}><Navigation size={14} />{routeStatus === "loading" ? "OSRM · строим дорожные маршруты" : routeStatus === "ready" ? "OSRM · маршруты по дорожной сети" : "OSRM недоступен · резервная геометрия"}</div></div>;
}

function JobTable({ jobs, engineers, onOpen, limit }: { jobs: Job[]; engineers: Engineer[]; onOpen: (id: string) => void; limit?: number }) { return <div className="job-table"><div className="job-row table-head"><span>Время</span><span>Заявка</span><span>Адрес</span><span>Инженер</span><span>Статус SLA</span><span /></div>{jobs.slice(0, limit ?? jobs.length).map(job => { const engineer = engineers.find(item => item.id === job.engineerId); return <button className="job-row job-row-button" key={job.id} onClick={() => onOpen(job.id)}><span className="job-time">{job.time}</span><span><i className={`job-tone ${job.tone}`} /><b>№ {job.id}</b><small>{job.kind}</small></span><span><b>{job.area}</b><small>{job.address}</small></span><span className="assigned">{engineer ? <><i style={{ background: engineer.color }}>{engineer.initials}</i><b>{engineer.name}</b></> : <b>Не назначена</b>}</span><span><Badge className={job.risk ? "sla risk" : "sla"}>{job.risk ? <AlertTriangle /> : <Clock3 />}{job.risk ? "Нет маршрута" : "В окне"}</Badge></span><span className="row-location"><MapPin /></span></button>; })}</div>; }
function RequestsView({ jobs, engineers, onOpen, onAdd }: { jobs: Job[]; engineers: Engineer[]; onOpen: (id: string) => void; onAdd: () => void }) { const unassigned = jobs.filter(job => !job.engineerId).length; return <section className="page-view"><div className="view-summary"><article><span>Из CSV и формы</span><strong>{jobs.length}</strong><small>заявок в текущем плане</small></article><article><span>Назначено VRPTW</span><strong>{jobs.length - unassigned}</strong><small>{((jobs.length - unassigned) / jobs.length * 100).toFixed(1)}% плана</small></article><article><span>Без назначения</span><strong>{unassigned}</strong><small>нет допустимого окна или ресурса</small></article></div><section className="panel queue-panel full-table"><div className="panel-header"><div><h2>Все заявки</h2><p>Источник CSV · три региона</p></div><button className="plain-button" onClick={onAdd}><Plus />Добавить заявку</button></div><JobTable jobs={jobs} engineers={engineers} onOpen={onOpen} /></section></section>; }
function EngineersView({ engineers, result, onOpen }: { engineers: Engineer[]; result: OptimizationResult; onOpen: (id: string) => void }) { const plans = new Map(result.routes.map(route => [route.engineerId, route])); const active = result.routes.length; const avg = active ? Math.round(result.routes.reduce((sum, route) => sum + route.load, 0) / active) : 0; return <section className="page-view"><div className="view-summary"><article><span>Доступно</span><strong>{engineers.length}</strong><small>бригад из контрольного CSV</small></article><article><span>На маршрутах</span><strong>{active}</strong><small>имеют назначенные работы</small></article><article><span>Средняя загрузка</span><strong>{avg}%</strong><small>по длительности смены</small></article></div><div className="engineer-card-grid">{engineers.map(engineer => { const route = plans.get(engineer.id); return <button key={engineer.id} className="engineer-card" onClick={() => onOpen(engineer.id)}><div className="engineer-card-head"><span className="avatar large" style={{ background: `${engineer.color}18`, color: engineer.color }}>{engineer.initials}</span><div><strong>{engineer.name}</strong><small>{engineer.region} · {engineer.route}</small></div><b style={{ color: engineer.color }}>{route?.load ?? 0}%</b></div><Progress value={route?.load ?? 0} className="load-progress" style={{ ["--primary" as string]: engineer.color }} /><div className="engineer-card-meta"><span><b>{route?.stops.length ?? 0}</b> заявок</span><span><b>{formatDistance(route?.distanceKm ?? 0)}</b></span><span><b>{engineer.skills.length}</b> навыков</span></div><small className="open-route">Открыть маршрут на карте</small></button>; })}</div></section>; }
function AnalyticsView({ result }: { result: OptimizationResult }) { const saved = result.baseline.distanceKm ? Math.round((1 - result.metrics.distanceKm / result.baseline.distanceKm) * 100) : 0; const maxJobs = Math.max(...result.zones.map(item => item.jobs)); return <section className="page-view"><div className="view-summary"><article><span>SLA вовремя</span><strong>{result.metrics.slaPercent}%</strong><small>{result.metrics.late} опозданий</small></article><article><span>Изменение пробега</span><strong>{saved > 0 ? "−" : "+"}{Math.abs(saved)}%</strong><small>{formatDistance(Math.abs(result.baseline.distanceKm - result.metrics.distanceKm))}</small></article><article><span>Назначено</span><strong>{result.metrics.assigned}/{result.metrics.total}</strong><small>VRPTW за {result.runtimeMs} мс</small></article></div><div className="analytics-grid"><article className="panel analytics-panel"><div className="panel-header"><div><h2>Заявки по зонам</h2><p>Пересчитывается из CSV и срочных заявок</p></div></div><div className="zone-chart">{result.zones.map(zone => <div key={zone.name}><span>{zone.name}</span><div><i style={{ width: `${zone.jobs / maxJobs * 100}%` }} /></div><strong>{zone.jobs}</strong></div>)}</div></article><article className="panel analytics-panel"><div className="panel-header"><div><h2>SLA по зонам</h2><p>Доля допустимых назначений</p></div></div><div className="sla-chart">{result.zones.map(zone => <div key={zone.name}><div className="sla-ring" style={{ ["--value" as string]: `${zone.sla * 3.6}deg` }}><strong>{zone.sla}%</strong></div><span>{zone.name}</span></div>)}</div></article><article className="panel analytics-panel wide"><div className="panel-header"><div><h2>Пробег: исходный и VRPTW</h2><p>Контрольное распределение сравнивается с текущим планом</p></div></div><div className="distance-bars">{result.zones.map(zone => { const ratio = zone.baselineDistance ? Math.min(100, zone.distance / zone.baselineDistance * 100) : 0; return <div key={zone.name}><span>{zone.name}</span><div className="distance-track"><i className="baseline" style={{ width: "100%" }} /><i className="optimized" style={{ width: `${ratio}%` }} /></div><strong>{formatDistance(zone.distance)}</strong></div>; })}</div><div className="analytics-legend"><span><i className="baseline" />Контрольное распределение</span><span><i className="optimized" />VRPTW-план</span></div></article></div></section>; }

export default function Dashboard() {
  const [view, setView] = useState<ViewId>("plan"); const [region, setRegion] = useState<"Все зоны" | Region>("Все зоны"); const [compare, setCompare] = useState(false); const [replanned, setReplanned] = useState(false); const [urgentOpen, setUrgentOpen] = useState(false); const [mobileNavOpen, setMobileNavOpen] = useState(false); const [selectedJobId, setSelectedJobId] = useState<string | null>(null); const [selectedEngineerId, setSelectedEngineerId] = useState<string | null>(null); const [theme, setTheme] = useState<ThemeId>("light"); const [themeOpen, setThemeOpen] = useState(false); const [routingState, setRoutingState] = useState<RoutingState>("loading"); const [extraJobs, setExtraJobs] = useState<Job[]>([]); const [optimizing, setOptimizing] = useState(false); const [formError, setFormError] = useState("");
  const [urgentForm, setUrgentForm] = useState({ address: "", region: "Юго-восток" as Region, start: "13:00", end: "14:30", kind: "Авария", equipment: "Рефлектометр", transport: "Автомобиль" });
  const allJobs = useMemo(() => [...sourceJobs, ...extraJobs], [extraJobs]); const result = useMemo(() => optimizeVrptw(sourceEngineers, allJobs), [allJobs]); const plannedJobs = result.jobs; const visibleJobs = useMemo(() => plannedJobs.filter(job => region === "Все зоны" || job.region === region), [plannedJobs, region]); const baselineJobs = useMemo(() => allJobs.filter(job => region === "Все зоны" || job.region === region), [allJobs, region]); const selectedJob = plannedJobs.find(job => job.id === selectedJobId) ?? null; const selectedEngineer = sourceEngineers.find(item => item.id === selectedJob?.engineerId); const routeByEngineer = useMemo(() => new Map(result.routes.map(route => [route.engineerId, route])), [result.routes]); const visibleEngineers = useMemo(() => sourceEngineers.filter(engineer => region === "Все зоны" || engineer.region === region), [region]);
  useEffect(() => { const saved = window.localStorage.getItem("fieldflow-theme") as ThemeId | null; if (saved && themes.some(item => item.id === saved)) { // eslint-disable-next-line react-hooks/set-state-in-effect
    setTheme(saved); } }, []); useEffect(() => { document.documentElement.dataset.theme = theme; window.localStorage.setItem("fieldflow-theme", theme); }, [theme]);
  const selectEngineer = useCallback((id: string) => { setSelectedEngineerId(current => current === id ? null : id); setSelectedJobId(null); }, []); const selectJob = useCallback((id: string) => { setSelectedJobId(id); setSelectedEngineerId(plannedJobs.find(item => item.id === id)?.engineerId ?? null); }, [plannedJobs]); const updateRoutingState = useCallback((state: RoutingState) => setRoutingState(state), []); const navigate = useCallback((next: ViewId) => { setView(next); setMobileNavOpen(false); }, []); const openEngineerOnMap = useCallback((id: string) => { setSelectedEngineerId(id); setSelectedJobId(null); setView("plan"); }, []);
  const optimize = useCallback(() => { setOptimizing(true); setTimeout(() => { setReplanned(true); setCompare(true); setOptimizing(false); }, 120); }, []);
  const addUrgent = useCallback(async () => { setFormError(""); if (!urgentForm.address.trim()) { setFormError("Укажите адрес заявки"); return; } const start = Number(urgentForm.start.slice(0, 2)) * 60 + Number(urgentForm.start.slice(3)); const end = Number(urgentForm.end.slice(0, 2)) * 60 + Number(urgentForm.end.slice(3)); if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) { setFormError("Проверьте временное окно"); return; } let coordinates = regionCenters[urgentForm.region]; try { coordinates = await new BackendGeocodingProvider("nominatim").geocode(urgentForm.address) ?? coordinates; } catch { /* fallback */ } const id = `URG-${Date.now().toString().slice(-6)}`; const job: Job = { id, time: `${urgentForm.start}–${urgentForm.end}`, windowStart: start, windowEnd: end, area: urgentForm.region, address: urgentForm.address, kind: urgentForm.kind, tone: "amber", region: urgentForm.region, engineerId: null, baselineEngineerId: null, coordinates, risk: false, equipment: urgentForm.equipment, requiredTransport: urgentForm.transport, priority: 10, serviceMinutes: 60, source: "Срочная форма", status: "Новая" }; setExtraJobs(current => [...current, job]); setReplanned(true); setCompare(true); setUrgentOpen(false); setSelectedJobId(id); setUrgentForm(current => ({ ...current, address: "" })); }, [urgentForm]);
  const titles = { plan: ["План работ", "17 августа 2026 · VRPTW по трём регионам"], requests: ["Заявки", "CSV и срочные работы"], team: ["Инженеры", "Ресурсы и рассчитанная загрузка"], analytics: ["Аналитика", "Показатели текущего VRPTW-плана"] } as const; const saving = result.baseline.distanceKm ? Math.round((1 - result.metrics.distanceKm / result.baseline.distanceKm) * 100) : 0;
  return <main className="app-shell">{mobileNavOpen && <button className="mobile-nav-backdrop" aria-label="Закрыть меню" onClick={() => setMobileNavOpen(false)} />}<aside className={`sidebar${mobileNavOpen ? " mobile-open" : ""}`}><div className="sidebar-brand-row"><Logo /><button className="mobile-nav-close" aria-label="Закрыть меню" onClick={() => setMobileNavOpen(false)}><X /></button></div><nav aria-label="Основная навигация"><button className={`nav-item${view === "plan" ? " active" : ""}`} onClick={() => navigate("plan")}><Route /><span>Планирование</span></button><button className={`nav-item${view === "requests" ? " active" : ""}`} onClick={() => navigate("requests")}><Wrench /><span>Заявки</span><b>{plannedJobs.length}</b></button><button className={`nav-item${view === "team" ? " active" : ""}`} onClick={() => navigate("team")}><UsersRound /><span>Инженеры</span></button><button className={`nav-item${view === "analytics" ? " active" : ""}`} onClick={() => navigate("analytics")}><BarChart3 /><span>Аналитика</span></button></nav><div className="sidebar-bottom"><button className="nav-item theme-nav" onClick={() => setThemeOpen(open => !open)}><SunMoon /><span>Тема</span></button><button className="nav-item"><CircleHelp /><span>Помощь</span></button><div className="profile"><span>ДК</span><div><strong>Диспетчер</strong><small>В сети</small></div><MoreHorizontal size={17} /></div></div></aside><section className="workspace" id="plan"><header className="topbar"><button className="mobile-menu" aria-label="Открыть меню" aria-expanded={mobileNavOpen} onClick={() => setMobileNavOpen(true)}><Menu /></button><div><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div><div className="top-actions"><button className="theme-button" onClick={() => setThemeOpen(open => !open)}><Contrast /><span>{themes.find(item => item.id === theme)?.name}</span><ChevronDown /></button><button className="search"><Search /><span>Найти заявку</span><kbd>⌘ K</kbd></button><button className="icon-button" aria-label="Уведомления"><Bell /><i /></button><Button className="urgent-button" onClick={() => setUrgentOpen(true)}><Zap />Срочная заявка</Button></div></header>
    {themeOpen && <div className="theme-menu" role="menu">{themes.map(item => <button key={item.id} className={theme === item.id ? "active" : ""} onClick={() => { setTheme(item.id); setThemeOpen(false); }}><span className="theme-swatches">{item.colors.map(color => <i key={color} style={{ background: color }} />)}</span><b>{item.name}</b>{theme === item.id && <Check />}</button>)}</div>}
    {view === "plan" && <><div className="filter-row"><Tabs defaultValue="day"><TabsList><TabsTrigger value="day">День</TabsTrigger><TabsTrigger value="week">Неделя</TabsTrigger></TabsList></Tabs><button className="date-control"><CalendarDays />17 авг. 2026<ChevronDown /></button><div className="region-select">{(["Все зоны", "Восток", "Юго-восток", "Югоцентр"] as const).map(item => <button key={item} className={region === item ? "selected" : ""} onClick={() => { setRegion(item); setSelectedEngineerId(null); setSelectedJobId(null); }}>{item}</button>)}</div><div className="plan-state"><span className={routingState === "ready" ? "state-dot" : routingState === "loading" ? "state-dot changed" : "state-dot risk-dot"} />{routingState === "ready" ? "OSRM подключён" : routingState === "loading" ? "Строим маршруты" : "Резервный режим"}</div></div>
      {replanned && <div className="impact-banner"><span><Sparkles /></span><div><strong>VRPTW-план рассчитан за {result.runtimeMs} мс</strong><p>Назначено {result.metrics.assigned} из {result.metrics.total}; временные окна и ресурсы проверены.</p></div><button onClick={() => { setReplanned(false); setCompare(false); }}>Скрыть сравнение</button></div>}
      <section className="metric-grid"><article><div className="metric-head"><span className="metric-icon purple"><Wrench /></span><small>Назначено</small><Badge className="metric-badge">{result.metrics.unassigned} без маршрута</Badge></div><strong>{result.metrics.assigned}<em>/ {result.metrics.total}</em></strong><p>из CSV и срочных заявок</p></article><article><div className="metric-head"><span className="metric-icon teal"><Route /></span><small>Пробег VRPTW</small><Badge className="metric-badge good">{saving > 0 ? "−" : "+"}{Math.abs(saving)}%</Badge></div><strong>{result.metrics.distanceKm.toFixed(1).replace(".", ",")}<em> км</em></strong><p>исходный: {formatDistance(result.baseline.distanceKm)}</p></article><article><div className="metric-head"><span className="metric-icon orange"><Clock3 /></span><small>SLA вовремя</small><Badge className="metric-badge good">{result.metrics.late} опозданий</Badge></div><strong>{result.metrics.slaPercent}%</strong><p>жёсткие временные окна</p></article><article><div className="metric-head"><span className="metric-icon blue"><Database /></span><small>Данные CSV</small><Badge className="metric-badge">{csvMeta.regions.length} зоны</Badge></div><strong>{csvMeta.rows}<em> строк</em></strong><p>{sourceEngineers.length} бригад из контроля</p></article></section>
      <section className="content-grid"><article className="panel map-panel"><div className="panel-header"><div><h2>Маршруты</h2><p>{visibleEngineers.length} инженеров · {visibleJobs.length} заявок · {region}</p></div><div className="legend"><span><i className="legend-solid" />VRPTW</span><span><i className="legend-dash" />Исходный</span><button className={compare ? "active" : ""} onClick={() => setCompare(value => !value)}><Layers3 />{compare ? "Скрыть сравнение" : "Сравнить"}</button></div></div><MapCanvas visibleJobs={visibleJobs} baselineJobs={baselineJobs} engineers={sourceEngineers} selectedEngineerId={selectedEngineerId} selectedJobId={selectedJobId} compare={compare} onSelectEngineer={selectEngineer} onSelectJob={selectJob} onRoutingState={updateRoutingState} /></article><article className="panel routes-panel"><div className="panel-header"><div><h2>Загрузка</h2><p>Результат оптимизатора</p></div><button className="plain-button" onClick={() => { setSelectedEngineerId(null); setSelectedJobId(null); }}>Все</button></div><div className="engineer-list">{visibleEngineers.slice(0, 12).map(engineer => { const route = routeByEngineer.get(engineer.id); return <button className={`engineer${selectedEngineerId === engineer.id ? " selected" : ""}`} key={engineer.id} onClick={() => selectEngineer(engineer.id)}><div className="avatar" style={{ background: `${engineer.color}18`, color: engineer.color }}>{engineer.initials}</div><div className="engineer-main"><div><strong>{engineer.name}</strong><span>{minutesLabel(engineer.shiftStart)}–{minutesLabel(engineer.shiftEnd)}</span></div><Progress value={route?.load ?? 0} className="load-progress" style={{ ["--primary" as string]: engineer.color }} /></div><div className="engineer-meta"><strong>{route?.stops.length ?? 0}</strong><span>заявок</span><small>{formatDistance(route?.distanceKm ?? 0)}</small></div></button>; })}</div><button className="optimize-button" disabled={optimizing} onClick={optimize}><Sparkles />{optimizing ? "Считаем…" : "Пересчитать VRPTW"}<span>ограничения</span></button></article></section>
      <section className="panel queue-panel"><div className="panel-header"><div><h2>Ближайшие работы</h2><p>{visibleJobs.length} заявок из текущего плана</p></div><button className="plain-button" onClick={() => setUrgentOpen(true)}><Plus />Добавить заявку</button></div><JobTable jobs={visibleJobs} engineers={sourceEngineers} onOpen={selectJob} limit={12} /></section></>}
    {view === "requests" && <RequestsView jobs={plannedJobs} engineers={sourceEngineers} onOpen={selectJob} onAdd={() => setUrgentOpen(true)} />}{view === "team" && <EngineersView engineers={sourceEngineers} result={result} onOpen={openEngineerOnMap} />}{view === "analytics" && <AnalyticsView result={result} />}</section>
  <Dialog open={urgentOpen} onOpenChange={setUrgentOpen}><DialogContent className="urgent-dialog"><DialogHeader><DialogTitle>Новая срочная заявка</DialogTitle><DialogDescription>Адрес будет геокодирован, затем заявка войдёт в VRPTW с повышенным приоритетом.</DialogDescription></DialogHeader><div className="urgent-form"><label className="wide"><span>Адрес</span><Input value={urgentForm.address} onChange={event => setUrgentForm(value => ({ ...value, address: event.target.value }))} placeholder="Москва, ул. Люблинская, 72" /></label><label><span>Регион</span><select value={urgentForm.region} onChange={event => setUrgentForm(value => ({ ...value, region: event.target.value as Region }))}><option>Восток</option><option>Юго-восток</option><option>Югоцентр</option></select></label><label><span>Тип работы</span><Input value={urgentForm.kind} onChange={event => setUrgentForm(value => ({ ...value, kind: event.target.value }))} /></label><label><span>Начало окна</span><Input type="time" value={urgentForm.start} onChange={event => setUrgentForm(value => ({ ...value, start: event.target.value }))} /></label><label><span>Окончание окна</span><Input type="time" value={urgentForm.end} onChange={event => setUrgentForm(value => ({ ...value, end: event.target.value }))} /></label><label><span>Оборудование</span><select value={urgentForm.equipment} onChange={event => setUrgentForm(value => ({ ...value, equipment: event.target.value }))}><option>Рефлектометр</option><option>GPON</option><option>ONT</option></select></label><label><span>Транспорт</span><select value={urgentForm.transport} onChange={event => setUrgentForm(value => ({ ...value, transport: event.target.value }))}><option>Автомобиль</option></select></label></div>{formError && <p className="form-error">{formError}</p>}<div className="dialog-note"><Sparkles /><span><b>Что учтёт оптимизатор</b>Навыки, оборудование, транспорт, смену, приоритет и временное окно.</span></div><DialogFooter><Button variant="outline" onClick={() => setUrgentOpen(false)}>Отмена</Button><Button onClick={() => void addUrgent()}><Zap />Добавить и пересчитать</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(selectedJob)} onOpenChange={open => !open && setSelectedJobId(null)}><DialogContent className="explain-dialog"><DialogHeader><DialogTitle>{selectedJob?.engineerId ? "Почему выбрано это назначение" : "Заявка не назначена"}</DialogTitle><DialogDescription>Заявка № {selectedJob?.id} · {selectedJob?.area}</DialogDescription></DialogHeader>{selectedJob?.engineerId ? <><div className="decision-score"><span><Sparkles /></span><div><b>{selectedEngineer?.name}</b><p>Допустимое назначение VRPTW</p></div><strong>{selectedJob.priority > 1 ? "P1" : "P2"}</strong></div><div className="reason-list"><p><i>1</i><span><b>Навык и оборудование совместимы</b>{selectedJob.kind} · {selectedJob.equipment}</span></p><p><i>2</i><span><b>Временное окно соблюдено</b>{selectedJob.time}, смена инженера не превышена.</span></p><p><i>3</i><span><b>Минимальный прирост маршрута</b>Выбран вариант с наименьшим увеличением пробега.</span></p></div></> : <div className="dialog-note"><AlertTriangle /><span><b>Нет допустимого назначения</b>Не совпали навык, ресурс или свободное время в окне.</span></div>}<DialogFooter><Button onClick={() => setSelectedJobId(null)}>Понятно</Button></DialogFooter></DialogContent></Dialog></main>;
}
